---
development:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>

test:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>

production:
  AMADEUS_KEY: <KEY GOES HERE>
  AMADEUS_SECRET: <SECRET GOES HERE>